# Exported from Render on 2025-05-09T01:50:51Z
services:
- type: web
  name: goVPN
  runtime: go
  repo: https://github.com/itxtoledo/goVPN
  plan: free
  envVars:
  - key: NETWORK_EXPIRY_DAYS
    sync: false
  - key: CLEANUP_INTERVAL_HOURS
    sync: false
  - key: SUPABASE_KEY
    sync: false
  - key: SUPABASE_URL
    sync: false
  - key: WRITE_BUFFER_SIZE
    sync: false
  - key: READ_BUFFER_SIZE
    sync: false
  - key: PING_INTERVAL_SECONDS
    sync: false
  - key: IDLE_TIMEOUT_SECONDS
    sync: false
  - key: LOG_LEVEL
    sync: false
  - key: MAX_CLIENTS_PER_NETWORK
    sync: false
  - key: ALLOW_ALL_ORIGINS
    sync: false
  - key: PORT
    sync: false
  region: oregon
  buildCommand: go build -tags netgo -ldflags '-s -w' -o app
  startCommand: ./app
  rootDir: cmd/server
version: "1"
